# Generated by Django 5.1.2 on 2025-09-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visibility', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('collapse', models.CharField(default='expand_issue', max_length=255)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('show_historic_incidents', models.BooleanField(default=True)),
                ('visibility', models.BooleanField(default=False)),
                ('status', models.CharField(default='operational', max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('component_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.componentgroup')),
            ],
            options={
                'ordering': ['component_group', 'order', 'pk'],
            },
        ),
    ]
