version: '3.8'

services:
  cpu-monitor:
    build: .
    container_name: cpu-monitor
    volumes:
      - /proc:/host/proc
    env_file:
      - ../.env
    restart: unless-stopped
  ec2-monitor:
    build: .
    container_name: ec2-monitor
    env_file:
      - ../.env
    environment:
      - SCRIPT=ec2_monitor
    restart: unless-stopped