apiVersion: v1
kind: ConfigMap
metadata:
  name: status-page-config
data:
  configuration.py: |
    ALLOWED_HOSTS = ['*']
    DATABASE = {
        'NAME': 'statuspage',
        'USER': 'statuspage',
        'PASSWORD': 'password123',
        'HOST': 'postgres',
        'PORT': '',
        'CONN_MAX_AGE': 300,
    }
    REDIS = {
        'tasks': {
            'HOST': 'redis',
            'PORT': 6379,
            'PASSWORD': '',
            'DATABASE': 0,
            'SSL': False,
        },
        'caching': {
            'HOST': 'redis',
            'PORT': 6379,
            'PASSWORD': '',
            'DATABASE': 1,
            'SSL': False,
        }
    }
    SECRET_KEY = 'PB7EvHFvCqvmUKUKr0DRj43b3a5UpDHfaoVh1SrTySUGlcPAPCq52aA3VcLcTBZKZzw'
    SITE_URL = 'http://localhost'
    STATIC_ROOT = '/app/static'