# Generated by Django 5.1.2 on 2025-09-04 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('visibility', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=True)),
                ('status', models.CharField(default='investigating', max_length=255)),
                ('impact', models.CharField(default='none', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('components', models.ManyToManyField(blank=True, related_name='incidents', to='components.component')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('visibility', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=True)),
                ('template_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='investigating', max_length=255)),
                ('impact', models.CharField(default='none', max_length=255)),
                ('update_component_status', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=65536)),
                ('components', models.ManyToManyField(blank=True, related_name='+', to='components.component')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.CharField(max_length=65536)),
                ('new_status', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
