apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status-page-tls
  namespace: default
spec:
  secretName: status-page-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - statuspage-benami.com