apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: status-page-sa
      containers:
      - name: web
        image: "992382545251.dkr.ecr.us-east-1.amazonaws.com/benami:status-page"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Copying configuration from ConfigMap..."
            cp /config/configuration.py /app/statuspage/statuspage/configuration.py
            # Update password in configuration
            sed -i "s/'PASSWORD': '',/'PASSWORD': '${POSTGRES_PASSWORD}',/" /app/statuspage/statuspage/configuration.py
            cat > /app/statuspage/gunicorn.py << 'EOF'
            bind = '0.0.0.0:8001'
            workers = 5
            threads = 3
            timeout = 120
            max_requests = 5000
            max_requests_jitter = 500
            EOF
            # Patch the original entrypoint to use our RDS/Redis endpoints
            sed -i "s/pg_isready -h postgres/pg_isready -h $DB_HOST/g" /entrypoint.sh
            sed -i "s/redis-cli -h redis/redis-cli -h $REDIS_HOST/g" /entrypoint.sh
            sed -i "s/'HOST': 'postgres'/'HOST': '$DB_HOST'/g" /entrypoint.sh
            sed -i "s/'HOST': 'redis'/'HOST': '$REDIS_HOST'/g" /entrypoint.sh
            exec /entrypoint.sh
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: POSTGRES_PASSWORD
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: POSTGRES_PASSWORD
        - name: SERVICE_NAME
          value: "web"
        - name: DB_HOST
          value: "benami-postgres.cx248m4we6k7.us-east-1.rds.amazonaws.com"
        - name: REDIS_HOST
          value: "benami-redis.7fftml.ng.0001.use1.cache.amazonaws.com"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: status-page-config
