name: Terraform Infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options: [apply, destroy]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        if: ${{ inputs.action == 'apply' }}
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: ${{ inputs.action == 'apply' }}
        working-directory: infra
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: ${{ inputs.action == 'destroy' }}
        working-directory: infra
        run: terraform destroy -auto-approve
